Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,64 +1,67 @@
 jobs:
   build:
     docker:
-      - image: cimg/base:stable                   # similar to "image" in GitLab
+      - image: python:3.6                   # similar to "image" in GitLab
     steps:
       - checkout
-      - run: echo "This is a build step"          # similar to "script" in GitLab
+      - run: |                              # similar to "script" in GitLab
+          pip install -r requirements.txt
+          python manage.py check
 
   test:
     docker:
-      - image: cimg/base:stable
+      - image: python:3.6
     steps:
       - checkout
-      - run: echo "This is a test step"
-
-  release:
-    machine: true                                        # What is this for?
-    steps:
-      - checkout
-
       - run: |
-          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
-          docker build -t $DOCKER_USERNAME/django.nv .   # Build the application into Docker image
-          docker push $DOCKER_USERNAME/django.nv         # Push the image into registry
+          pip install -r requirements.txt
+          python manage.py test taskManager
+
+  secret_scanning:
+    machine: true
+    steps:
+      - checkout
+
+      - run:
+          command: docker run --rm -v $(pwd):/src hysnsec/trufflehog filesystem /src --json > trufflehog-output.json || true
+
+      - store_artifacts:
+          path: trufflehog-output.json
+          destination: trufflehog-artifact
+          when: always
 
   integration:
     docker:
-      - image: cimg/base:stable
+      - image: python:3.6
     steps:
       - checkout
       - run:
           command: |
             echo "This is an integration step"
             exit 1
-          when: on_fail # Even if the job fails, continue to the next jobs
+          when: on_fail         # Even if the job fails, continue to the next stages
 
   prod:
     docker:
-      - image: cimg/base:stable
+      - image: python:3.6
     steps:
       - checkout
-      - run: echo "This is a deploy step"
-
-  artifact:
-    docker:
-      - image: cimg/base:stable
-    steps:
-      - checkout
-      - run: echo "hello" > hello.txt
-      - store_artifacts:
-          path: hello.txt
-          destination: artifact-file
+      - run: echo "This is a deploy step."
 
 workflows:
   version: 2
   django:
     jobs:
       - build
-      - test
-      - release
-      - integration
+      - test:
+          requires:
+            - build
+      - secret_scanning:
+          requires:
+            - test
+      - integration:
+          requires:
+            - secret_scanning
       - prod:
           type: approval
           requires:
